from tests import *
from registration_tests import *
from login_tests import *
from collection_tests import *
from label_tests import *
from reservation_tests import *
from labelNote_tests import *
from status_tests import *
from image_tests import *
from inventoryItem_tests import *
from noninventoryitem_tests import *
from consumableitem_tests import *
from action_type_test import *
from new_inventory_item_tests import *