from django.conf.urls import patterns, url

urlpatterns = patterns('website.views',
                       url(r'^collections/$', 'views.collectionList'),
                       url(r'^collections/(?P<pk>[0-9]+)$', 'views.collectionDetail'),
                       url(r'^labels/$', 'views.labelList'),
                       url(r'^labels/(?P<pk>[0-9]+)$', 'views.labelDetail'),
                       url(r'^inventoryitems/$', 'views.inventoryItemList'),
                       url(r'^inventoryitems/(?P<pk>[0-9]+)$', 'views.inventoryItemDetail'),
                       url(r'^locations/$', 'views.locationList'),
                       url(r'^locations/(?P<pk>[0-9]+)$', 'views.locationDetail'),
                       url(r'^models/$', 'views.itemModelList'),
                       url(r'^models/(?P<pk>[0-9]+)$', 'views.itemModelDetail'),
                       url(r'^reservations/$', 'views.reservationList'),
                       url(r'^reservations/(?P<pk>[0-9]+)$', 'views.reservationDetail'),
                       url(r'^labelNotes/$', 'views.labelNoteList'),
                       url(r'^labelNotes/(?P<pk>[0-9]+)$', 'views.labelNoteDetail'),
                       url(r'^images/$', 'views.imageList'),
                       url(r'^images/(?P<pk>[0-9]+)$', 'views.imageDetail'),
                       url(r'^statuses/$', 'views.statusList'),
                       url(r'^statuses/(?P<pk>[0-9]+)$', 'views.statusDetail'),
                       url(r'^inventoryItems/$', 'views.inventoryItemList'),
                       url(r'^inventoryItems/(?P<pk>[0-9]+)$', 'views.inventoryItemDetail'),
                       url(r'^brands/$', 'views.itemBrandList'),
                       url(r'^brands/(?P<pk>[0-9]+)$', 'views.itemBrandDetail'),
                       url(r'^brands/(?P<bn>.+)$', 'views.itemBrandDetail'),
                       url(r'^actions/$', 'views.actionTypeList'),
                       url(r'^actions/(?P<pk>[0-9]+)$', 'views.actionTypeDetail'),
                       url(r'^itemHistory/(?P<fk>[0-9]+)$', 'views.itemHistoryDetail'),
                       url(r'^categoryHierarchy/', 'views.categoryHierarchy'),
                       url(r'^autocomplete/', 'views.autocomplete'),
                       url(r'^itemHistory/(?P<fk>[0-9]+)$', 'itemHistoryDetail'),
                       url(r'^reservationHistory/(?P<fk>[0-9]+)$', 'reservationHistoryDetail'),)



